# Generated by Django 4.2.6 on 2023-11-14 00:45

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainversion',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='data',
            field=models.FileField(upload_to=apps.users.models.train_data_file_path),
        ),
    ]
