# Generated by Django 4.2.6 on 2023-11-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trainversion_trained_alter_traindata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainversion',
            name='loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
